#!/bin/sh
set -e

if [ "$1" = remove ] && command -v systemctl >/dev/null 2>&1; then
    systemctl stop discord-music-bot.service >/dev/null 2>&1 || true
    systemctl disable discord-music-bot.service >/dev/null 2>&1 || true
fi

exit 0
